version: 2.1

jobs:
  build:
    docker:
      - image: cimg/dotnet:8.0
    steps:
      - checkout
      - run: dotnet restore firstapp/firstapp.csproj
      - run: dotnet build firstapp/firstapp.csproj --configuration Release
      - run: dotnet test firstapp/firstapp.csproj --no-build --verbosity normal

workflows:
  build-and-test:
    jobs:
      - build
